const STORAGE='project-challenge-mobile-v1';
const defaultState=()=>({name:'Project 30',days:30,start:today(),mode:'all',percent:80,manifesto:'我将在接下来的挑战中，坚持完成自己的计划。',rules:[{id:id(),icon:'☀️',text:'8点前起床'},{id:id(),icon:'🧘',text:'完成不被打扰的晨间仪式'},{id:id(),icon:'🏃',text:'运动1小时'},{id:id(),icon:'📚',text:'阅读10页书'},{id:id(),icon:'🎯',text:'专注技能／项目1小时'},{id:id(),icon:'🥗',text:'健康饮食'},{id:id(),icon:'📝',text:'记录过程与进步'}],rewards:[{day:10,text:'给自己一个小奖励'},{day:20,text:'安排一次放松活动'},{day:30,text:'完成挑战奖励'}],entries:{}});
let state=load();let currentDate=today();
function id(){return Math.random().toString(36).slice(2,9)}function today(){const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}function load(){try{return JSON.parse(localStorage.getItem(STORAGE))||defaultState()}catch{return defaultState()}}function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function dayNo(date){return Math.floor((new Date(date+'T12:00:00')-new Date(state.start+'T12:00:00'))/86400000)+1}function dateForDay(n){const d=new Date(state.start+'T12:00:00');d.setDate(d.getDate()+n-1);return d.toISOString().slice(0,10)}function entry(date){return state.entries[date]||(state.entries[date]={checks:{},wake:'',sleep:'',mood:'',gratitude:'',reflection:'',progress:''})}function completion(e){const total=state.rules.length;if(!total)return 0;return state.rules.filter(r=>e.checks?.[r.id]).length/total}function complete(e){const c=completion(e);return state.mode==='all'?c===1:c>=state.percent/100}
function setView(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={today:'今日打卡',calendar:'挑战日历',rules:'挑战规则',rewards:'阶段奖励',settings:'挑战设置'};$('#pageTitle').textContent=titles[view];$('#pageTitleDesktop').textContent=titles[view];if(view==='calendar')renderCalendar();if(view==='rules')renderRuleEditor();if(view==='rewards')renderRewardEditor();if(view==='settings')renderSettings();window.scrollTo({top:0,behavior:'smooth'})}
function renderHeader(){const label=state.name.toUpperCase();$('#challengeLabel').textContent=label;$('#challengeLabelDesktop').textContent=label;$('#dayTotal').textContent='/'+state.days;const completed=Object.values(state.entries).filter(complete).length;const pct=Math.min(100,Math.round(completed/state.days*100));$('#progressPercent').textContent=pct+'%';$('#progressRing').style.background=`conic-gradient(var(--accent) ${pct*3.6}deg,#343432 0)`;$('#sideProgress').textContent=`${completed} / ${state.days} 天`}
function renderToday(){const e=entry(currentDate);$('#entryDate').value=currentDate;const n=dayNo(currentDate);$('#dayNumber').textContent=n;$('#wakeTime').value=e.wake||'';$('#sleepHours').value=e.sleep||'';$('#mood').value=e.mood||'';$('#gratitude').value=e.gratitude||'';$('#reflection').value=e.reflection||'';$('#progressNote').value=e.progress||'';$('#todayRules').innerHTML='';state.rules.forEach(r=>{const row=document.createElement('label');row.className='check-item';row.innerHTML=`<input type="checkbox" ${e.checks?.[r.id]?'checked':''}><span>${esc(r.icon||'✓')}</span><b>${esc(r.text)}</b>`;row.querySelector('input').onchange=ev=>{e.checks[r.id]=ev.target.checked;save();renderSummary()};$('#todayRules').append(row)});renderSummary();renderHeader()}
function renderSummary(){const e=entry(currentDate),done=state.rules.filter(r=>e.checks?.[r.id]).length,total=state.rules.length,pct=total?Math.round(done/total*100):0;$('#doneCount').textContent=done;$('#ruleCount').textContent=`/${total} 项`;$('#todayBar').style.width=pct+'%';$('#completionHint').textContent=complete(e)?'今天已达成挑战标准':'还差 '+Math.max(0,total-done)+' 项'}
function renderCalendar(){$('#calendarTitle').textContent=`${state.name} 打卡记录`;$('#dayGrid').innerHTML='';for(let i=1;i<=state.days;i++){const date=dateForDay(i),e=state.entries[date],c=e?completion(e):0,b=document.createElement('button');b.className='day-tile'+(e?(complete(e)?' done':c>0?' partial':''):'')+(date===currentDate?' active':'');b.innerHTML=`${i}<small>${date.slice(5)}</small>`;b.onclick=()=>{currentDate=date;setView('today');renderToday()};$('#dayGrid').append(b)}}
function renderRuleEditor(){$('#ruleEditor').innerHTML='';state.rules.forEach((r,i)=>{const row=document.createElement('div');row.className='edit-row';row.innerHTML=`<input value="${esc(r.icon||'')}" aria-label="图标"><input value="${esc(r.text)}" aria-label="规则"><button class="delete-btn">删除</button>`;const ins=row.querySelectorAll('input');ins[0].oninput=()=>{r.icon=ins[0].value;save()};ins[1].oninput=()=>{r.text=ins[1].value;save()};row.querySelector('button').onclick=()=>{state.rules.splice(i,1);save();renderRuleEditor();renderToday()};$('#ruleEditor').append(row)})}
function renderRewardEditor(){$('#rewardEditor').innerHTML='';state.rewards.forEach((r,i)=>{const row=document.createElement('div');row.className='edit-row reward-row';row.innerHTML=`<input type="number" min="1" max="${state.days}" value="${r.day}"><input value="${esc(r.text)}"><button class="delete-btn">删除</button>`;const ins=row.querySelectorAll('input');ins[0].oninput=()=>{r.day=+ins[0].value;save()};ins[1].oninput=()=>{r.text=ins[1].value;save()};row.querySelector('button').onclick=()=>{state.rewards.splice(i,1);save();renderRewardEditor()};$('#rewardEditor').append(row)})}
function renderSettings(){$('#challengeName').value=state.name;$('#challengeDays').value=state.days;$('#startDate').value=state.start;$('#completionMode').value=state.mode;$('#completionPercent').value=state.percent;$('#manifesto').value=state.manifesto;$('#percentField').classList.toggle('hidden',state.mode!=='percent')}
function bindAuto(){[['wakeTime','wake'],['sleepHours','sleep'],['mood','mood'],['gratitude','gratitude'],['reflection','reflection'],['progressNote','progress']].forEach(([a,b])=>$('#'+a).addEventListener('input',e=>{entry(currentDate)[b]=e.target.value;save()}));$('#entryDate').onchange=e=>{currentDate=e.target.value;renderToday()}}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>setView(b.dataset.jump));
$('#addRuleBtn').onclick=()=>{state.rules.push({id:id(),icon:'✨',text:'新规则'});save();renderRuleEditor()};$('#addRewardBtn').onclick=()=>{state.rewards.push({day:Math.min(state.days,10),text:'新的阶段奖励'});save();renderRewardEditor()};$('#completionMode').onchange=e=>$('#percentField').classList.toggle('hidden',e.target.value!=='percent');
$('#saveSettingsBtn').onclick=()=>{state.name=$('#challengeName').value.trim()||`Project ${$('#challengeDays').value}`;state.days=Math.max(1,Math.min(365,+$('#challengeDays').value||30));state.start=$('#startDate').value||today();state.mode=$('#completionMode').value;state.percent=Math.max(1,Math.min(100,+$('#completionPercent').value||80));state.manifesto=$('#manifesto').value;save();renderToday();alert('设置已保存')};
$('#resetBtn').onclick=()=>{if(confirm('确定清空当前挑战的全部记录吗？')){state.entries={};save();renderToday()}};
const dlg=$('#challengeDialog');function openNew(){ $('#newStart').value=today();dlg.showModal()}$('#newChallengeBtn').onclick=openNew;$('#newChallengeBtnDesktop').onclick=openNew;$('#createChallengeBtn').onclick=e=>{e.preventDefault();const d=Math.max(1,Math.min(365,+$('#newDays').value||30));state=defaultState();state.days=d;state.name=$('#newName').value.trim()||`Project ${d}`;state.start=$('#newStart').value||today();state.rewards=[{day:Math.min(10,d),text:'阶段奖励'},{day:d,text:'完成挑战奖励'}];currentDate=state.start;save();dlg.close();renderToday();setView('today')};
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${state.name.replace(/\s+/g,'_')}_backup.json`;a.click();URL.revokeObjectURL(a.href)}$('#exportBtn').onclick=exportData;$('#exportBtnMobile').onclick=exportData;
bindAuto();renderToday();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
